[package]
name = "rust_sandbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mock = []

[dependencies]
libc = "0.2"
lazy_static = "1.4"

[target.'cfg(loom)'.dependencies]
loom = "0.7"
